name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'

      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          echo "Building with VITE_API_BASE_URL=$VITE_API_BASE_URL"
          npm ci
          npm run build
          ls -la dist
        env:
          VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }}

      - name: Show built bundle excerpt
        working-directory: ./frontend
        run: |
          grep -n "todo-backend-func" dist -R || true
          head -n 50 $(grep -ril "ListTasks" dist | head -n1) || true

      - name: Upload prebuilt frontend to Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ""                      # upload from repo root
          output_location: "frontend/dist"      # point at your built artifact
